In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline
import matplotlib.pyplot as plt


In [6]:
churn_df=pd.read_csv(r'C:\Users\SRIDHAR N\Downloads\ChurnData.csv')
churn_df.head(10)
#loading data from computer memory and reading first 10 rows of data

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
5    68.0  52.0     17.0   120.0  1.0    24.0    0.0       1.0       0.0   
6    42.0  40.0      7.0    37.0  2.0     8.0    1.0       1.0       1.0   
7     9.0  21.0      1.0    17.0  2.0     2.0    0.0       0.0       0.0   
8    35.0  50.0     26.0   140.0  2.0    21.0    0.0       1.0       0.0   
9    49.0  51.0     27.0    63.0  4.0    19.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
5    20.70  ...    0.0       0.0       0.0     0.0    0.0    3.030    3.240   
6     8.25  ...    0.0       1.0       1.0     1.0    1.0    2.110    3.157   
7     2.90  ...    0.0       0.0       0.0     0.0    0.0    1.065    3.240   
8     6.50  ...    0.0       0.0       1.0     1.0    0.0    1.872    3.314   
9    12.85  ...    0.0       1.0       1.0     0.0    1.0    2.553    3.248   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  
5  4.787      1.0    0.0  
6  3.611      4.0    0.0  
7  2.833      1.0    0.0  
8  4.942      3.0    0.0  
9  4.143      2.0    0.0  

[10 rows x 28 columns]

In [13]:
churn_df=churn_df[['tenure','age', 'address','income','ed','employ','equip','callcard','wireless','churn']]
churn_df['chrun']=churn_df['churn'].astype('int')
churn_df.head()
#reading the the data from row zero
#specify the the labels of data and convert the churn data as integer

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  chrun  
0    1.0      1  
1    1.0      1  
2    0.0      0  
3    0.0      0  
4    0.0      0

In [15]:
churn_df.shape
#to knowm the size of the  data

(200, 11)

In [32]:
X=np.asarray(churn_df[['tenure','age', 'address','income','ed','employ','equip','callcard','wireless']])
X[0:5]
#read only the independent (first five only)variables from given data.

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.,   1.,   1.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.,   0.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.,   1.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.,   1.,   0.]])

In [33]:
y=np.asarray(churn_df[['churn']])
y[0:5]
#reading the dependent variable from data (churn data), first five only

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.]])

In [39]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]
#importing the library form python for preprocesing data

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695,  0.64686916,  1.56469673],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695, -1.54590766, -0.63910148],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695, -1.54590766, -0.63910148],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ,  0.64686916,  1.56469673],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695,  0.64686916, -0.63910148]])

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

#splitting the data by using python library as train data, and test data with size 80:20
#Print function is used  to disply the  training sets and test datas 

Train set: (160, 9) (160, 1)
Test set: (40, 9) (40, 1)


In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR=LogisticRegression(C=0.01,solver='liblinear').fit(X_train,y_train)
LR
#IMPORTING LOGISTIC REGRESSION FROM LIBRARY AND FINDING THE BEST FIT FOR GIVEN CASE

C:\Users\SRIDHAR N\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [52]:
yhat=LR.predict(X_test)
yhat

#where yhat is regression line value and here we are predicting the the churn or  not for test case 

array([0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1.])

In [53]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob
#checking the probabilty of final class  

array([[0.58711718, 0.41288282],
       [0.56650898, 0.43349102],
       [0.5313329 , 0.4686671 ],
       [0.66722528, 0.33277472],
       [0.53481231, 0.46518769],
       [0.59508358, 0.40491642],
       [0.49995014, 0.50004986],
       [0.56532893, 0.43467107],
       [0.39939231, 0.60060769],
       [0.59368426, 0.40631574],
       [0.54844546, 0.45155454],
       [0.58957413, 0.41042587],
       [0.52439771, 0.47560229],
       [0.41344893, 0.58655107],
       [0.68930146, 0.31069854],
       [0.51576247, 0.48423753],
       [0.4969602 , 0.5030398 ],
       [0.46038301, 0.53961699],
       [0.47010467, 0.52989533],
       [0.57170621, 0.42829379],
       [0.50781873, 0.49218127],
       [0.49802608, 0.50197392],
       [0.66938224, 0.33061776],
       [0.49625351, 0.50374649],
       [0.47635919, 0.52364081],
       [0.73040145, 0.26959855],
       [0.45111513, 0.54888487],
       [0.49187403, 0.50812597],
       [0.4927476 , 0.5072524 ],
       [0.73618723, 0.26381277],
       [0.